// <auto-generated />
using System;
using AXD_BookingFast.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AXD_BookingFast.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250625160128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            City = "Barranquilla",
                            Name = "Barranquilla"
                        },
                        new
                        {
                            Id = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            City = "Cali",
                            Name = "Cali"
                        },
                        new
                        {
                            Id = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            City = "Cartagena",
                            Name = "Cartagena"
                        },
                        new
                        {
                            Id = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            City = "Bogotá",
                            Name = "Bogotá"
                        });
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 1,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 2,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 4,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 5,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 6,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 7,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 8,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 9,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 10,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 11,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 12,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 13,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 14,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 15,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 16,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 17,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 18,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 19,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 20,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000021"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 21,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000022"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 22,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000023"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 23,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000024"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 24,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000025"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 25,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000026"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 26,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000027"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 27,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000028"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 28,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000029"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 29,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000030"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 30,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000031"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 31,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000032"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 32,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000033"),
                            HotelId = new Guid("f7b9ce9b-2ff0-4bc5-b42a-46948a0f8136"),
                            MaxPeople = 4,
                            Number = 33,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000034"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 1,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000035"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 2,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000036"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 3,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000037"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 4,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000038"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 5,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000039"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 6,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000040"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 7,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000041"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 8,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000042"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 9,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000043"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 10,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000044"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 11,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000045"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 12,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000046"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 13,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000047"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 14,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000048"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 15,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000049"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 16,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000050"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 17,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000051"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 18,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000052"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 19,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000053"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 20,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000054"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 21,
                            RoomType = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000055"),
                            HotelId = new Guid("ea2c6bb1-9515-4443-bfb8-b80cfbfe15ef"),
                            MaxPeople = 6,
                            Number = 22,
                            RoomType = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000056"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 1,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000057"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 2,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000058"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000059"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 4,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000060"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 5,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000061"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 6,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000062"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 7,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000063"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 8,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000064"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 9,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000065"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 10,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000066"),
                            HotelId = new Guid("7e7db5c0-7d1d-4e9c-b226-6e2d1390c7f4"),
                            MaxPeople = 8,
                            Number = 11,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000067"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 1,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000068"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 2,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000069"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 3,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000070"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 4,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000071"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 5,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000072"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 6,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000073"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 7,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000074"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 8,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000075"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 9,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000076"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 10,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000077"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 11,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000078"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 12,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000079"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 13,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000080"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 14,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000081"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 15,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000082"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 16,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000083"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 17,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000084"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 18,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000085"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 19,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000086"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 20,
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000087"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 21,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000088"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 22,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000089"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 23,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000090"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 24,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000091"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 25,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000092"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 26,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000093"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 27,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000094"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 28,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000095"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 29,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000096"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 30,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000097"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 31,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000098"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 32,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000099"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 33,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000100"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 34,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000101"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 35,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000102"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 36,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000103"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 37,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000104"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 38,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000105"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 39,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000106"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 40,
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000107"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 41,
                            RoomType = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000108"),
                            HotelId = new Guid("95c27ad9-3d5f-4f32-8e5e-bd4d91a9907d"),
                            MaxPeople = 6,
                            Number = 42,
                            RoomType = 3
                        });
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.RoomRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<int>("SeasonType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomRates");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeasonType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("AXD_BookingFast.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Room", b =>
                {
                    b.HasOne("AXD_BookingFast.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AXD_BookingFast.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
